import { styles } from "../styles.slint";
import { PlayerState } from "../globals.slint";
import { controls } from "controls.slint";

export component sidePlayer inherits Rectangle  {
    background: styles.theme.background;
    border-top-left-radius: styles.border-radius;
    // border-radius: styles.border-radius;

    property <bool> has-selection: PlayerState.selected-index >= 0 && PlayerState.selected-index < PlayerState.tracks.length;

    VerticalLayout {
        spacing: styles.margin / 2;
        padding: styles.margin;
        alignment: center;

        if !root.has-selection: HorizontalLayout {
            alignment: center;
            Image {
                source: @image-url("../assets/icon_nobg.svg");
                width: 100px;
                height: 100px;
                colorize: styles.theme.container.ghost-text;
            }
        }

        if !root.has-selection: Text {
            text: "Nothing playing... Click a track to play it!";
            color: styles.theme.container.ghost-text;
            horizontal-alignment: center;
            overflow: elide;
        }

        if root.has-selection: VerticalLayout {
            Text {
                text: PlayerState.tracks[PlayerState.selected-index].title;
                color: styles.theme.container.text;
                font-size: 16px;
                font-weight: 700;
                horizontal-alignment: center;
                overflow: elide;
            }

            Text {
                text: PlayerState.tracks[PlayerState.selected-index].artist;
                color: styles.theme.container.text;
                horizontal-alignment: center;
                overflow: elide;
            }
        }

        controls {}
    }
}
