import { styles } from "../styles.slint";
import { PlayerState } from "../globals.slint";

export component sidePlayer inherits Rectangle  {
    background: styles.theme.container.background;
    border-radius: styles.border-radius;

    property <bool> has-selection: PlayerState.selected-index >= 0 && PlayerState.selected-index < PlayerState.tracks.length;

    VerticalLayout {
        spacing: styles.margin / 2;
        padding: styles.margin;
        alignment: center;

        if !root.has-selection: Text {
            text: "nothing playing... click a track to play it! ♪ヾ(＞ω＜)ゞ";
            color: styles.theme.container.text;
            opacity: 0.5;
            horizontal-alignment: center;
            overflow: elide;
        }

        if root.has-selection: VerticalLayout {
            Text {
                text: PlayerState.tracks[PlayerState.selected-index].title;
                color: styles.theme.container.text;
                font-size: 16px;
                horizontal-alignment: center;
                overflow: elide;
            }

            Text {
                text: PlayerState.tracks[PlayerState.selected-index].artist;
                color: styles.theme.container.text;
                opacity: 0.6;
                horizontal-alignment: center;
                overflow: elide;
            }
        }

    }
}
