import { styles } from "../styles.slint";
import { Track } from "../common.slint";
import { PlayerState } from "../globals.slint";


export component track {
    in property <Track> info;
    in property <int> index;

    callback clicked();

    property <bool> playing: root.index == PlayerState.selected-index;

    Rectangle {
        border-radius: styles.border-radius;
        background: root.playing
            ? styles.theme.container.floating
            : area.has-hover
                ? styles.theme.container.floating.with-alpha(50%)
                : transparent;
        height: 40px;
        horizontal-stretch: 1;

        // animate background {
        //     duration: 100ms;
        //     easing: styles.easing;
        // }

        area := TouchArea {
            mouse-cursor: pointer;
            clicked => { root.clicked(); }
        }

        HorizontalLayout {
            padding: styles.margin;
            spacing: styles.margin;
            Text {
                text: root.info.title;
                color: styles.theme.container.text;
                vertical-alignment: center;
                horizontal-stretch: 1;
            }
            Text {
                text: root.info.artist + " • " + root.info.dur;
                color: styles.theme.container.text;
                vertical-alignment: center;
                opacity: 0.6;
                overflow: elide;
            }
        }
    }
}
