import { styles } from "../styles.slint";
import { track } from "track.slint";
import { ListView } from "std-widgets.slint";
import { PlayerState } from "../globals.slint";

export component trackList inherits Rectangle  {
    background: styles.theme.container.background;
    border-radius: styles.border-radius;

    if PlayerState.tracks.length == 0 : Text {
        text: "No tracks found! :(";
        color: styles.theme.container.text;
        opacity: 0.5;
    }

    HorizontalLayout {
        padding: styles.margin;

        ListView{
            for info[i] in PlayerState.tracks : Rectangle {
                height: 40px + styles.margin;

                track {
                    info: info;
                    index: i;
                    clicked => { PlayerState.select-track(i); }

                    x: styles.margin / 2;
                    width: parent.width - styles.margin;
                }
            }
        }
    }
}
