import { styles } from "../styles.slint";
import { ScrollView, ListView, Button } from "std-widgets.slint";
import { DirsState } from "../globals.slint";

export component settingsView inherits HorizontalLayout {
    spacing: styles.margin / 2;

    Rectangle {
        horizontal-stretch: 1;
        border-radius: styles.border-radius;
        vertical-stretch: 1;
        background: styles.theme.container.background;

        VerticalLayout {
            padding: styles.margin;
            spacing: styles.margin;

            Rectangle {
                background: styles.theme.container.floating;
                border-radius: styles.border-radius;
                horizontal-stretch: 1;
                height: 32px;

                area := TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        DirsState.add-directory();
                    }
                }

                Image {
                    source: @image-url("../assets/icons/add_dir.svg");
                    width: 22px;
                    height: 22px;
                    colorize: styles.theme.container.text;
                }
            }

            Rectangle {
                background: styles.theme.container.floating;
                border-radius: styles.border-radius;
                HorizontalLayout {
                padding: styles.margin;
                    ListView {
                        for dir[index] in DirsState.directories: Rectangle{
                        background: styles.theme.container.background;
                        border-radius: styles.border-radius;
                        height: 32px;
                            HorizontalLayout {
                                padding: styles.margin / 2;
                                spacing: styles.margin / 2;
                                padding-left: styles.margin;

                                Text{
                                    text: dir;
                                    color: styles.theme.container.text;
                                    horizontal-alignment: left;
                                    vertical-alignment: center;
                                    overflow: elide;
                                    horizontal-stretch: 1;
                                }

                                rm-button := Rectangle {
                                    width: 24px;
                                    height: 24px;
                                    border-radius: styles.border-radius;
                                    background: rm-touch.has-hover ? #e81123 : styles.theme.container.floating;
                                    animate background { duration: 100ms; easing: styles.easing; }


                                    Image {
                                        source: @image-url("../assets/icons/delete.svg");
                                        width: 16px;
                                        height: 16px;
                                        colorize: rm-touch.has-hover ? white : styles.theme.container.text;
                                    }

                                    rm-touch := TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => { DirsState.rm-directory(index); }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
