import { styles } from "../styles.slint";
import { ScrollView, ListView } from "std-widgets.slint";
import { DirsState } from "../globals.slint";

export component settingsView inherits HorizontalLayout {
    spacing: styles.margin / 2;

    Rectangle {
        horizontal-stretch: 1;
        border-radius: styles.border-radius;
        vertical-stretch: 1;
        background: styles.theme.container.background;

        VerticalLayout {
            padding: styles.margin;
            spacing: styles.margin;

            Rectangle {
                background: styles.theme.container.floating;
                border-radius: styles.border-radius;
                horizontal-stretch: 1;
                height: 32px;

                area := TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        DirsState.add-directory();
                    }
                }

                Text {
                    text: "+ Directory";
                    color: styles.theme.container.text;
                }
            }

            Rectangle {
                background: styles.theme.background;
                border-radius: styles.border-radius;
                HorizontalLayout {
                padding: styles.margin;
                    ListView {
                        for dir in DirsState.directories: Text{
                            text: dir;
                            color: styles.theme.container.text;
                            overflow: elide;
                        }
                    }
                }
            }
        }
    }
}
