import { Track } from "common.slint";

export global PlayerState {
    in-out property <[Track]> tracks: [];
    in-out property <int> selected-index: -1;
    in-out property <bool> playing: false;
    in-out property <float> volume: 0.5;

    callback select-track(int);
    callback toggle();
    callback set-volume(float);
}

export global CurrentView {
    in-out property <int> selected-view: 0;
}

export global DirsState {
    in-out property <[string]> directories: [];
    callback add-directory();
    callback rm-directory(int);
}

export global WindowState {
    callback minimize();
    callback toggle-fullscreen();
    callback close();
}
