import { Track } from "common.slint";

export global PlayerState {
    in-out property <[Track]> tracks: [];
    in-out property <int> selected-index: -1;

    callback select-track(int);
}

export global CurrentView {
    in-out property <int> selected-view: 0;
}

export global DirsState {
    in-out property <[string]> directories: [];
    callback add-directory();
}

export global WindowState {
    callback minimize();
    callback toggle-fullscreen();
    callback close();
}
