struct container{
    background: brush,
    floating: brush,
    ghost-text: brush,
    text: brush,
    border: brush,
    color: brush,
}

struct mTheme{
    background: brush,
    container: container,
}

export global styles{
    out property <length> margin: 8px;
    out property <length> border-radius: 8px;
    out property <easing> easing: ease-out;
    in-out property <bool> isDark: true;

    out property <mTheme> theme: isDark ? {
        background: #191919,
        container: {
            background: #1e1e1e,
            floating: #313131,
            ghost-text: #767676,
            text: #e9e9e9,
            border: #2b2b2b,
            color: #f2003d,
        },
    } : {
        background: #fafafa,
        container: {
            background: #f5f5f5,
            floating: #e6e6e6,
            ghost-text: #9a9a9a,
            text: #171717,
            border: #e7e7e7,
            color: #f2003d,
        },
    };
}
